# Generated by Django 3.0.5 on 2020-05-02 14:24

import customer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_auto_20200430_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=10, validators=[customer_app.models.Customer.contact_validator]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=30, null=True, unique=True),
        ),
    ]
