# Generated by Django 3.0.5 on 2020-05-02 16:08

import customer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_auto_20200502_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[customer_app.models.Customer.min_length_validator]),
        ),
    ]
