# Generated by Django 3.0.5 on 2020-04-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
        ('accounts', '0004_auto_20200429_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_app.Customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
