# Generated by Django 3.0.5 on 2020-04-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200430_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
