# Generated by Django 3.0.5 on 2020-04-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_total_bal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bal',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_bal',
        ),
    ]
