# Generated by Django 3.0.5 on 2020-05-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200502_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='desc',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
