# Generated by Django 3.0.5 on 2020-05-02 16:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200502_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gave',
            field=models.IntegerField(default=0, validators=[accounts.models.Account.validate_amount]),
        ),
        migrations.AlterField(
            model_name='account',
            name='got',
            field=models.IntegerField(default=0, validators=[accounts.models.Account.validate_amount]),
        ),
    ]
