# Generated by Django 3.0.5 on 2020-05-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0005_auto_20200502_2138'),
        ('accounts', '0012_auto_20200502_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='customer_app.Customer'),
        ),
    ]
